
os: linux
dist: focal
arch: arm64-graviton2
group: edge
virt: vm

jobs:
  include:
  - language: ruby
    script:
      - ruby hello.rb

  - language: cpp
    compiler: clang
    script:
      - g++ -nostartfiles main.cpp

  - language: python
    script:
      - python hello.py

  - language: node_js
    node_js:
      - node
    script:
      - node hello.js

  - language: java
    jdk: openjdk8
    script:
      - mvn clean install

  - language: go
    script:
      - go run ./hello.go
 
  - language: php
    php: '7.4'
    script:
      - php hello.php

  - language: perl
    perl: '5.30'
    before_install:
         - "sudo apt-get install -qq unixodbc unixodbc-dev"
         - "curl -L https://cpanmin.us | perl - --sudo App::cpanminus"        
         - "nvm install node && nvm use node"
         - "npm install -g dredd"
         - cd ..
         - cd travis_test_p1_3/
         - "bundle install"
    install:
    - cpanm -f -n $(cat .perlmodules | tr "\n" " ")   
    script:
    - perl hello.PL

  - language: csharp
    script:
      - csc hello.cs
      - mono hello.exe

